name: Update Gist
 
on:
  push:
    branches: master

  schedule:
    - cron: "12 */12 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e7411f7042085bb37c3361a4ed910366
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
